"""add fuel_type to airplane

Revision ID: 51df15a0073e
Revises: 359492fc3a98
Create Date: 2020-06-09 12:06:02.049167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51df15a0073e'
down_revision = '359492fc3a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplanes', sa.Column('fuel_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('airplanes', 'fuel_type')
    # ### end Alembic commands ###
