"""fix column name fuel_consumption

Revision ID: da2eb1e17a1c
Revises: 6b90ff4d5430
Create Date: 2020-06-08 18:27:34.401660

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da2eb1e17a1c'
down_revision = '6b90ff4d5430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplanes', sa.Column('fuel_consumption', sa.Float(), nullable=True))
    op.drop_column('airplanes', 'fuel_comsumption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('airplanes', sa.Column('fuel_comsumption', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('airplanes', 'fuel_consumption')
    # ### end Alembic commands ###
